### ISSUE TITLE
Did you see that paper ?

### ISSUE THREAD

**Issue by oliviernguyenquoc** [gkordo/s2vs#1]
https://www.semanticscholar.org/reader/93d3b14ac1c5b86dc7ea2eef54d4541e4e2df57f

This work seems to be very similar.
Did you take inspiration of it ? 

How do you think do you perform vs this work ?

If you release the code open source, it already make a huge difference.

Anyway, your paper is very insightful !

**Comment by gkordo** [comment]
@oliviernguyenquoc, many thanks for your question. This is a very inspiring work, and indeed the two methods are pretty close since both develop an SSL training process using a similar set of augmentations. Therefore, we have included the published version of this work, i.e. the [VRL [31]](https://dl.acm.org/doi/10.1145/3477495.3532010) method, in our comparison to the state-of-the-art in Table 1. Yet, there are some key differences between the two approaches:

* In VRL, the authors build based on SSL for representation learning to train the backbone network for feature extraction and an aggregation network that extracts clip-level representations. The similarity function is a variant of the handcrafted Chamfer Similarity tailored for hashed vectors, which is **non-parametric**. In contrast, in our work, we opt to use SSL for similarity learning, so we train a **parametric** similarity function without altering the representation space. To this end, our backbone network remains frozen during training, and we train a ViSiL-based network on top.
* Another thing is that, in VRL, they build a training dataset **offline**, which means that the video pairs used in training are static, so fixed variations are seen by the network. Instead, we dynamically generate the video pairs **online** during training; hence our model is exposed to a larger variety of combinations.
* Also, the research problem that VRL target to address is near-duplicate video retrieval. However, we tailor our method to tackle a wide range of similarity-based problems, including copy (near-duplicate), incident and event video retrieval, and their detection counterparts.
* Finally, as noted, we plan to release our implementation to the public, including the training processed and pretrained models. Additionally, we rely solely on publicly available datasets to build our models.

I am closing this issue since it is not directly related to this repo. Feel free to ask anything if there are further queries.

**Comment by oliviernguyenquoc** [comment]
Very inspiring. Thank you for releasing your code. 

Congratulation !
